/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Calculate_sub calculate = new Calculate_sub();
        System.out.println(calculate.sub(2, 1));
    }
}
