/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {

    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.println(new App().getGreeting());     
        System.out.print("Sum of " + 2.0 + " and " + 3.0 + " is " + new AddCalc().AddCalculate());
        scanner.close();
    }

    

    
}
